require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GistsController do

  # This should return the minimal set of attributes required to create a valid
  # Gist. As you add validations to Gist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString",
      "url" => "MyString",
      "count" => 1 }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GistsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gists as @gists" do
      gist = Gist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gists).should eq([gist])
    end
  end

  describe "GET show" do
    it "assigns the requested gist as @gist" do
      gist = Gist.create! valid_attributes
      get :show, {:id => gist.to_param}, valid_session
      assigns(:gist).should eq(gist)
    end
  end

  describe "GET new" do
    it "assigns a new gist as @gist" do
      get :new, {}, valid_session
      assigns(:gist).should be_a_new(Gist)
    end
  end

  describe "GET edit" do
    it "assigns the requested gist as @gist" do
      gist = Gist.create! valid_attributes
      get :edit, {:id => gist.to_param}, valid_session
      assigns(:gist).should eq(gist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gist" do
        expect {
          post :create, {:gist => valid_attributes}, valid_session
        }.to change(Gist, :count).by(1)
      end

      it "assigns a newly created gist as @gist" do
        post :create, {:gist => valid_attributes}, valid_session
        assigns(:gist).should be_a(Gist)
        assigns(:gist).should be_persisted
      end

      it "redirects to the created gist" do
        post :create, {:gist => valid_attributes}, valid_session
        response.should redirect_to(Gist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gist as @gist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gist.any_instance.stub(:save).and_return(false)
        post :create, {:gist => { "name" => "invalid value" }}, valid_session
        assigns(:gist).should be_a_new(Gist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gist.any_instance.stub(:save).and_return(false)
        post :create, {:gist => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gist" do
        gist = Gist.create! valid_attributes
        # Assuming there are no other gists in the database, this
        # specifies that the Gist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gist.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => gist.to_param, :gist => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested gist as @gist" do
        gist = Gist.create! valid_attributes
        put :update, {:id => gist.to_param, :gist => valid_attributes}, valid_session
        assigns(:gist).should eq(gist)
      end

      it "redirects to the gist" do
        gist = Gist.create! valid_attributes
        put :update, {:id => gist.to_param, :gist => valid_attributes}, valid_session
        response.should redirect_to(gist)
      end
    end

    describe "with invalid params" do
      it "assigns the gist as @gist" do
        gist = Gist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gist.any_instance.stub(:save).and_return(false)
        put :update, {:id => gist.to_param, :gist => { "name" => "invalid value" }}, valid_session
        assigns(:gist).should eq(gist)
      end

      it "re-renders the 'edit' template" do
        gist = Gist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gist.any_instance.stub(:save).and_return(false)
        put :update, {:id => gist.to_param, :gist => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gist" do
      gist = Gist.create! valid_attributes
      expect {
        delete :destroy, {:id => gist.to_param}, valid_session
      }.to change(Gist, :count).by(-1)
    end

    it "redirects to the gists list" do
      gist = Gist.create! valid_attributes
      delete :destroy, {:id => gist.to_param}, valid_session
      response.should redirect_to(gists_url)
    end
  end

end
